name:                data-diff
version:             0.1.0.0
github:              "parsonsmatt/data-diff"
license:             BSD3
author:              "Matt Parsons"
maintainer:          "parsonsmatt@gmail.com"
copyright:           "Matt Parsons"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/parsonsmatt/data-diff#readme>

dependencies:
- base >= 4.12 && < 5
- text
- template-haskell

default-extensions:
  - StandaloneDeriving
  - FlexibleContexts
  - UndecidableInstances

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  data-diff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-diff
